language: node_js
sudo: false

cache:
  directories:
  - node_modules
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=mail@torounit.com
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=mail@torounit.com
before_script:
  - nvm install 8.6.0
  - npm install
script:
  - npm run build

after_success:
  - bash sh/deploy.sh
